# Edit this file to customize for your system.

# whether CodeGen+ is built
BUILD_CODEGEN = true
# BUILD_CODEGEN = false

# if SUIFHOME environment for SUIF 1.x exists, build for it!
ifneq ($(strip $(wildcard $(SUIFHOME))),)
BUILD_SUIF = true
else
BUILD_SUIF = false
endif

CC = g++
# CC = icc -Kc++ 
CFLAGS = -g
DEPENDENCE_CFLAGS = -M

AR = ar

INCL_PATH = -I$(BASEDIR)/basic/include -I../include
LIBS =
LIB_PATH =

# default installation path
ifeq ($(shell whoami), root)
DEST_DIR = /usr/local/
else
DEST_DIR = $(HOME)/
endif
# uncomment below to overwrite default path
# DEST_DIR =

# DO NOT CHANGE
OMEGA_BUILD_DATE = $(shell date +%m/%d/%Y)

